name: Release VS Code Theme

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install --include=dev

      - name: Check formatting with Prettier
        run: npx prettier --check . "!**/.vscode/**"

      - name: Ensure out directory exists
        run: mkdir -p out

      - name: Get next version tag (conventional commits)
        id: version
        uses: reecetech/version-increment@2024.10.1
        with:
          scheme: conventional_commits
          tag_prefix: v

      - name: Update package.json version
        run: |
          jq --arg v "$VERSION" '.version = $v' package.json > package.tmp.json
          mv package.tmp.json package.json
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Build theme package
        run: npm run package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.v-version }}
          name: Release ${{ steps.version.outputs.v-version }}
          files: out/dzsolarized-${{ steps.version.outputs.version }}.vsix
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: out/dzsolarized-${{ steps.version.outputs.version }}.vsix

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: bump version to $VERSION [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          VERSION: ${{ steps.version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ntfy:
    name: Ntfy
    if: github.event_name == 'push' && ${{ !cancelled() }}
    runs-on: ubuntu-latest
    needs: [build-and-release]
    steps:
      - name: Send success notification
        uses: niniyas/ntfy-action@v1.0.4
        if: ${{ !contains(needs.*.result, 'failure') }}
        with:
          url: "https://ntfy.cdzombak.net"
          topic: "gha-builds"
          priority: 3
          headers: '{"authorization": "Bearer ${{ secrets.NTFY_TOKEN }}"}'
          tags: white_check_mark
          title: ${{ github.event.repository.name }} ${{ needs.build-and-release.outputs.version }} available
          details: ${{ github.event.repository.name }} version ${{ needs.build-and-release.outputs.version }} is now available.
      - name: Send failure notification
        uses: niniyas/ntfy-action@v1.0.4
        if: ${{ contains(needs.*.result, 'failure') }}
        with:
          url: "https://ntfy.cdzombak.net"
          topic: "gha-builds"
          priority: 3
          headers: '{"authorization": "Bearer ${{ secrets.NTFY_TOKEN }}"}'
          tags: no_entry
          title: ${{ github.event.repository.name }} ${{ needs.build-and-release.outputs.version }} build failed
          details: Build failed for ${{ github.event.repository.name }} version ${{ needs.build-and-release.outputs.version }}.
