name: Release VS Code Theme

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install --include=dev

      - name: Check formatting with Prettier
        run: npx prettier --check .

      - name: Ensure out directory exists
        run: mkdir -p out

      - name: Get next version tag (conventional commits)
        id: version
        uses: reecetech/version-increment@2024.10.1
        with:
          scheme: conventional_commits
          tag_prefix: v

      - name: Update package.json version
        run: |
          jq --arg v "$VERSION" '.version = $v' package.json > package.tmp.json
          mv package.tmp.json package.json
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Build theme package
        run: vsce package --no-dependencies --out out/dzsolarized.vsix

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.v-version }}
          name: Release ${{ steps.version.outputs.v-version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload VSIX as release asset
        uses: softprops/action-gh-release@v2
        with:
          files: out/dzsolarized.vsix
          tag_name: ${{ steps.version.outputs.v-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: bump version to $VERSION [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          VERSION: ${{ steps.version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install --include=dev

      - name: Check formatting with Prettier
        run: npx prettier --check .

      - name: Ensure out directory exists
        run: mkdir -p out

      - name: Build theme package
        run: npm run package
